=== Oskareczkee/Strony-Internetowe/Website Project/XML/template.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
	<xs:element name="websitedata" type="websiteDataType"/>

	<xs:complexType name="websiteDataType">
		<xs:all>
			<xs:element name="languages" type="languagesType" minOccurs="0"></xs:element>
			<xs:element name="gallery" type="galleryType" minOccurs="0"></xs:element>
			<xs:element name="availableCountries" type="contactCountriesType" minOccurs="0"></xs:element>
			<xs:element name="lastUpdateDate" type="dateSimpleType"></xs:element>
		</xs:all>
	</xs:complexType>

	<!--for contact.html, select countries-->
	<xs:simpleType name="contactCountriesType">
		<xs:list itemType="xs:string"></xs:list>
	</xs:simpleType>

	<xs:complexType name="galleryType">
		<xs:choice maxOccurs="unbounded">
			<xs:element ref="image"></xs:element>
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="languagesType">
		<xs:sequence>
			<xs:element name="languageType" type="languageTypeType" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="languageTypeType">
		<xs:sequence>
			<xs:element name="language" type="languageType" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
		
		<xs:attribute name="type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="interpreted"></xs:enumeration>
					<xs:enumeration value="compiled"></xs:enumeration>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>

	<xs:attributeGroup name="linkAttributeGroup">
		<xs:attribute name="source" type="xs:anyURI" use="required"/>
	</xs:attributeGroup>

	<xs:complexType name="linkType">
		<xs:attributeGroup ref="linkAttributeGroup"></xs:attributeGroup>
	</xs:complexType>

	<xs:element name="image">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="linkType">
					<xs:attribute name="alt-text" use="optional" type="shortStringType"></xs:attribute>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="link">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="linkType"></xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="shortStringType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="50"></xs:maxLength>
			<xs:minLength value="1"></xs:minLength>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="longStringType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="5000"></xs:maxLength>
			<xs:minLength value="100"></xs:minLength>
		</xs:restriction>
	</xs:simpleType>

	<xs:group name="language-info">
		<xs:sequence>
			<xs:element name="date" type="xs:string" maxOccurs="1"></xs:element>

			<xs:element name="author" minOccurs="1">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="shortStringType">
							<xs:attribute name="alive" use="optional" default="yes">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="yes|no"></xs:pattern>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>

			<xs:element name="description" type="longStringType" maxOccurs="1"></xs:element>
			<xs:element ref="image" minOccurs="0" maxOccurs="1"></xs:element>
			<xs:element ref="link" minOccurs="0" maxOccurs ="unbounded"></xs:element>
		</xs:sequence>
	</xs:group>

	<xs:complexType name="languageType">
		<xs:group ref="language-info"/>
		<xs:attribute name="name" use="required" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:simpleType name="dateSimpleType">
		<xs:union memberTypes="xs:dateTime xs:date xs:gYearMonth xs:gYear"/>
	</xs:simpleType>

</xs:schema>

=== Oskareczkee/Strony-Internetowe/Website Project/XML/data.xml
<?xml version="1.0" encoding="UTF-8"?>

<websitedata xsi:noNamespaceSchemaLocation="template.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <languages>
		<languageType type="interpreted">
			<language name="JavaScript">
				<date>4 Grudnia 1995</date>
				<author alive="yes">Brendan Eich</author>
				<description>
						Najczęściej spotykanym zastosowaniem języka JavaScript są strony internetowe. Skrypty te służą najczęściej do zapewnienia interakcji poprzez reagowanie na zdarzenia, walidacji danych wprowadzanych w formularzach lub tworzenia złożonych efektów wizualnych. Skrypty JavaScriptu uruchamiane przez strony internetowe mają znacznie ograniczony dostęp do komputera użytkownika. Po stronie serwera JavaScript może działać w postaci node.js lub Ringo.
						W języku JavaScript można także pisać pełnoprawne aplikacje. Fundacja Mozilla udostępnia środowisko złożone z technologii takich jak XUL, XBL, XPCOM oraz JSLib. Umożliwiają one tworzenie korzystających z zasobów systemowych aplikacji o graficznym interfejsie użytkownika dopasowującym się do danej platformy. Przykładem aplikacji napisanych z użyciem JS i XUL może być klient IRC o nazwie ChatZilla, domyślnie dołączony do pakietu Mozilla. Microsoft udostępnia biblioteki umożliwiające tworzenie aplikacji JScript jako część środowiska Windows Scripting Host. Ponadto JScript.NET jest jednym z podstawowych języków środowiska .NET. Istnieje także stworzone przez IBM środowisko SashXB dla systemu Linux, które umożliwia tworzenie w języku JavaScript aplikacji korzystających z GTK+, GNOME i OpenLDAP. Platforma Node.js umożliwia pisanie aplikacji wiersza poleceń oraz aplikacji serwerowych. Node.js używany jest także w środowisku Electron, który umożliwia pisanie aplikacji GUI. Język JavaScript używany jest także na urządzeniach internetu rzeczy, robotów czy układów takich jak Arduino poprzez bibliotekę Johnny-Five.
				</description>
				<image source="Images/Languages/jsbg.png" alt-text="javascript image"/>
				<link source="https://pl.wikipedia.org/wiki/JavaScript" />
			</language>
			<language name="Python">
				<date>1991</date>
				<author alive="yes">Guido van Rossum</author>
				<description>
					Pythona stworzył we wczesnych latach 90. Guido van Rossum – jako następcę języka ABC, stworzonego w Centrum voor Wiskunde en Informatica (CWI – Centrum Matematyki i Informatyki w Amsterdamie). Van Rossum jest głównym twórcą Pythona, choć spory wkład w jego rozwój pochodzi od innych osób. Z racji kluczowej roli, jaką van Rossum pełnił przy podejmowaniu ważnych decyzji projektowych, często określano go przydomkiem „Benevolent Dictator for Life” (BDFL).
					Nazwa języka nie pochodzi od zwierzęcia lecz od serialu komediowego emitowanego w latach siedemdziesiątych przez BBC – „Monty Python’s Flying Circus” (Latający cyrk Monty Pythona). Projektant, będąc fanem serialu i poszukując nazwy krótkiej, unikalnej i nieco tajemniczej, uznał tę za świetną.
					Wersja 1.2 była ostatnią wydaną przez CWI. Od 1995 roku Van Rossum kontynuował pracę nad Pythonem w Corporation for National Research Initiatives (CNRI) w Reston w Wirginii, gdzie wydał kilka wersji Pythona, do 1.6 włącznie. W 2000 roku van Rossum i zespół pracujący nad rozwojem jądra Pythona przenieśli się do BeOpen.com by założyć zespół BeOpen PythonLabs. Pierwszą i jedyną wersją wydaną przez BeOpen.com był Python 2.0.
					Po wydaniu wersji 1.6 i opuszczeniu CNRI przez van Rossuma, który zajął się programowaniem komercyjnym, uznano za wysoce pożądane, by Pythona można było używać z oprogramowaniem dostępnym na licencji GPL. CNRI i Free Software Foundation (FSF) podjęły wspólny wysiłek w celu odpowiedniej modyfikacji licencji Pythona. Wersja 1.6.1 była zasadniczo identyczna z wersją 1.6, z wyjątkiem kilku drobnych poprawek oraz licencji, dzięki której późniejsze wersje mogły być zgodne z licencją GPL. Python 2.1 pochodzi zarówno od wersji 1.6.1, jak i 2.0.
					Po wydaniu Pythona 2.0 przez BeOpen.com Guido van Rossum i inni programiści z PythonLabs przeszli do Digital Creations. Cała własność intelektualna dodana od tego momentu, począwszy od Pythona 2.1 (wraz z wersjami alpha i beta), jest własnością Python Software Foundation (PSF), niedochodowej organizacji wzorowanej na Apache Software Foundation.
				</description>
				<image source="Images/Languages/pyghtonbg.jpg" alt-text="python image"/>
				<link source="https://pl.wikipedia.org/wiki/Python" />
			</language>
			<language name="PHP">
				<date>1995</date>
				<author alive="yes">Rasmus Lerdorf</author>
				<description>
					Pierwsza wersja PHP, rozpowszechniana pod nazwą PHP/FI (Personal Home Page/Forms Interpreter), została stworzona przez Rasmusa Lerdorfa w roku 1994 jako zestaw skryptów Perla służący do monitorowania internautów odwiedzających jego witrynę. Gdy ruch stał się zbyt duży, przepisał je w języku C, dodając przy tym nowe opcje. Niedługo później ludzie zaczęli prosić go o możliwość użycia tych narzędzi na swoich stronach, zatem 8 czerwca 1995 roku autor udostępnił publicznie kod źródłowy (PHP Tools 1.0). Już kilka miesięcy później projekt przekształcił się w zalążek znanego obecnie języka programowania, gdy został połączony z innym narzędziem Rasmusa Lerdorfa – Form Interpreter, które dało drugi człon nazwy. W 1997 roku pojawiło się PHP/FI 2.0, posiadające wtedy kilka tysięcy aktywnych użytkowników na całym świecie oraz obsługujące 50 tys. domen. Wersja ta spędziła większość „życia” na beta testach. Oficjalne wydanie było tylko jedno i ukazało się w listopadzie 1997 roku
				</description>
				<image source="Images/Languages/phpbg.jpg" alt-text="php image"/>
				<link source="https://pl.wikipedia.org/wiki/PHP" />
			</language>
		</languageType>
		
		<languageType type="interpreted">
			<language name="C++">
				<date>1983</date>
				<author alive="yes">Bjarne Stroustrup</author>
				<description>
					C++ – język programowania ogólnego przeznaczenia. Język został zaprojektowany przez Bjarne Stroustrupa jako rozszerzenie języka C o obiektowe mechanizmy abstrakcji danych i silną statyczną kontrolę typów. Zachowanie zgodności z językiem C na poziomie kodu źródłowego pozostaje jednym z podstawowych celów projektowych kolejnych standardów języka.
					Umożliwia abstrakcję danych oraz stosowanie kilku paradygmatów programowania: proceduralnego, obiektowego i generycznego, a także funkcyjnego i modularnego. Charakteryzuje się wysoką wydajnością kodu wynikowego, bezpośrednim dostępem do zasobów sprzętowych i funkcji systemowych, łatwością tworzenia i korzystania z bibliotek (napisanych w C++, C lub innych językach), niezależnością od konkretnej platformy sprzętowej lub systemowej (co gwarantuje wysoką przenośność kodów źródłowych) oraz niewielkim środowiskiem uruchomieniowym. Podstawowym obszarem jego zastosowań są aplikacje i systemy operacyjne.
					W latach 90. XX wieku język C++ zdobył pozycję jednego z najpopularniejszych języków programowania ogólnego przeznaczenia. Na początku XXI wieku liczbę programistów języka C++ szacowano na około 3 miliony
				</description>
				<image source="Images/Languages/cppbg.png" alt-text="c++ image"/>
				<link source="https://pl.wikipedia.org/wiki/C%2B%2B" />
			</language>

			<language name="Rust">
				<date>2010</date>
				<author alive="yes">Graydon Hoare</author>
				<description>
					Język zaprojektował Graydon Hoare w 2006 roku, w 2009 projekt został przyjęty pod skrzydła Mozilla Foundation. W 2010 Mozilla upubliczniła informację o języku. W 2011 roku kompilator języka, znany jako rustc, został z powodzeniem skompilowany przez samego siebie.
					Pierwsza numerowana wersja alfa została wydana w 2012 roku. 15 maja 2015 ukazała się wersja 1.0.
					8 lutego 2021 pięć firm (Mozilla, AWS, Google, Microsoft i Huawei) ogłosiły utworzenie Fundacji Rust.
					6 kwietnia 2021 Google ogłosił wsparcie dla języka Rust w ramach Android Open Source Project jako alternatywę dla języków C/C++.
					Rust wykorzystuje Cargo jako menadżer pakietów.
					Wiele organizacji wykorzystuje ten język programowania w zastosowaniach produkcyjnych. Obecnie dwoma największymi otwartymi projektami korzystającymi z języka Rust są: Servo oraz kompilator Rusta
				</description>
				<image source="Images/Languages/rustbg.jpg" alt-text="rust image"/>
				<link source="https://pl.wikipedia.org/wiki/Rust_(język_programowania)"/>
			</language>
		</languageType>
    </languages>

	<gallery>
		<image source="" alt-text="rust image"/>
		<image source="" alt-text="rust image"/>
		<image source="" alt-text="rust image"/>
		<image source="" alt-text="rust image"/>
		<image source="" alt-text="rust image"/>
		<image source="" alt-text="rust image"/>
		<image source="" alt-text="rust image"/>
	</gallery>

	<availableCountries>
		Polska
		Niemcy
		Słowacja
		Czechy
		Ukraina
		Litwa
		"Wielka Brytania"
	</availableCountries>

	<lastUpdateDate>2022-11-29</lastUpdateDate>
</websitedata>
